from types import SimpleNamespace as SN

def get_args():
  args = {
    'act_noise': 0.1,
    'action_range': None,
    'action_selector': None,
    'agent': 'rnn',
    'agent_output_type': None,
    'agent_return_logits': False,
    'batch_size': 1,  # default: 32
    'batch_size_run': 1,
    'buffer_algo': None,
    'buffer_chunk_size': None,
    'buffer_cpu_only': True,
    'buffer_device': None,
    'buffer_mode': 'transitions',
    'buffer_size': 5000,
    'buffer_warmup': 0,
    'checkpoint_path': '',
    'continuous_actions': False,
    'critic_lr': 0.01,
    'critic_train_reps': 1,
    'debug': False,
    'device': 'cuda',
    'discretize_actions': False,
    'double_q': False,
    'env': 'particle',
    'env_args': {
        'agent_view_radius': 1.5,
        'benchmark': False,
        'episode_limit': 25,
        'partial_obs': True,
        'scenario_name': 'continuous_pred_prey_3a',
        'score_function': 'min',
        'seed': 316342621,
        'state_last_action': False,
        'state_mode': 'all'
    },
    'epsilon_anneal_time': None,
    'epsilon_decay_mode': None,
    'epsilon_finish': None,
    'epsilon_start': None,
    'evaluate': False,
    'exploration_mode': 'gaussian',
    'final_ou_noise_scale': 0.0,
    'gamma': 0.85,
    'gated': False,
    'grad_norm_clip': 0.5,
    'hyper_initialization_nonzeros': 0,
    'hypernet_embed': 64,
    'hypernet_layers': 1,
    'label': 'default_label',
    'learn_interval': 1,
    'learner': 'facmac_learner',
    'learner_log_interval': 1,  # default: 2000
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 2000,
    'lr': 0.01,
    'mac': 'cqmix_mac',
    'mixer': 'qmix',
    'mixing_embed_dim': 64,
    'n_runners': None,
    'n_train': 1,
    "n_agents": 2,
    "n_actions": 30,
    "state_shape": 148,
    "obs_shape": 30, # 74 + 30
    'name': 'facmac_pp',
    'noise_clip': 0.5,
    'obs_agent_id': True,
    'obs_last_action': True,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'optimizer': 'adam',
    'optimizer_epsilon': 0.01,
    'ou_noise_scale': 0.3,
    'ou_sigma': 0.2,
    'ou_stop_episode': 100,
    'ou_theta': 0.15,
    'plot_loss_network': False,
    'q_embed_dim': 1,
    'q_nstep': 0,
    'recurrent_critic': False,
    'repeat_id': 1,
    'rnn_hidden_dim': 64,
    'run_mode': None,
    'runner': 'episode',
    'runner_log_interval': 2000,
    'runner_scope': 'episodic',
    'save_model': True,
    'load_model': True,
    'save_model_interval': 10,  # default: 10000 NOTE eval by 50 step
    'save_replay': False,
    'seed': 316342621,
    'skip_connections': False,
    'start_steps': 0,
    't_max': 150, # default: 2000000 NOTE eval by 100 step
    'target_update_interval': None,
    'target_update_mode': 'soft',
    'target_update_tau': 0.001,
    'td_lambda': 0.8,
    'test_greedy': None,
    'test_interval': 2000,
    'test_nepisode': 10,
    'testing_on': False,  # default: True
    'use_buffer_compression': False,
    'use_cuda': True,
    'use_tensorboard': False,
    'unique_token': 'facmac_pp',
    'verbose': False,
    'weight_decay': True,
    'weight_decay_factor': 0.0001
  }

  args = SN(**args)
  
  return args
